export const JSON_PLACEHOLDER_TODOS_TEXTS = {
  createButton: 'Create todo',
  createCompletedLabel: 'Completed',
  createTitleLabel: 'Title',
  deleteButton: 'Delete',
  emptyList: 'No todos found',
  completedStatus: 'Completed',
  loadingDetail: 'Loading todo...',
  loadingList: 'Loading todos...',
  nextPage: 'Next',
  noSelectedTodo: 'Select a todo to inspect details',
  pageLabel: 'Page',
  panelTitle: 'JSONPlaceholder Todos',
  patchButton: 'Patch',
  previousPage: 'Previous',
  refreshHint: 'JSONPlaceholder simulates writes and does not persist changes between requests.',
  replaceButton: 'Replace',
  requestError: 'Request failed',
  selectedTodoTitle: 'Selected todo',
  pendingStatus: 'Pending',
  todosListTitle: 'Todos',
  userIdLabel: 'User ID',
} as const;
